### ISSUE TITLE
hikaricp will be incompatible w/ codahale metrics 4.0

### ISSUE THREAD

**Issue by jgangemi** [brettwooldridge/HikariCP#335]
i wanted to try out the 4.0.0-SNAPSHOT release of codahale metrics, but the package name has changed from `com.codahale` to `io.dropwizard`, making it incompatible.

**Comment by brettwooldridge** [comment]
This will be handled in the release following 2.4.0.

**Comment by brettwooldridge** [comment]
Update: This is difficult to address from a build perspective until the 4.0.0 artifacts are released.  The issue will be resolved at that time.

**Comment by jklukas** [comment]
Looks like this is addressed in current versions and can likely be closed.

**Comment by brettwooldridge** [comment]
Really?

**Comment by jklukas** [comment]
My apologies. It indeed looks like the package is still `com.codahale.metrics` in the imports. I was confusing this with the change in maven artifact name, which is now `io.dropwizard.metrics:metrics-core`.

Looks like 4.0.0 is indeed still in development two years later and that's still the release that will change the package name. Sorry for the static here.

**Comment by jasonwinshell-br** [comment]
I am now using  HikariCP-3.1.0 with the latest metrics-core-5.0.0. In looking at the source for HikariConfig I still see a reference to the old codahale package and then exception when calling HikariConfig (indirectly) from .setMetricRegistry:

throw new IllegalArgumentException("Class must be instance of com.codahale.metrics.MetricRegistry or io.micrometer.core.instrument.MeterRegistry");

Isn't this fixed?

**Comment by jasonwinshell-br** [comment]
The HikariCP page indicates that HikariCP-3.1.0 is for Java 8/9.  The 2.x series still has the problem.

**Comment by djbehnke** [comment]
Does this have a resolution? I'm trying to use dropwizard with Hikari 3.2 but get a 
`IllegalArgumentException: Class must be instance of com.codahale.metrics.MetricRegistry or io.micrometer.core.instrument.MeterRegistry`

When following the pattern suggested here: https://stackoverflow.com/questions/28615203/how-do-i-configure-hikaricp-and-dropwizard-coda-hale-metrics-in-spring-boot-appl

It looks like the snippets causing this are the same in the latest version of Hikari.

**Comment by djbehnke** [comment]
I found a solution for my use case. There was no need for me to use dropwizard. HikariCP now has built in Prometheus metrics.

My setup likely differs from anyone who is reading this but the following snippet works seemlessly to add the Hikari metrics to our Prometheus registry using SpringBoot:

```
...
    @Bean
    public PrometheusMetricsTrackerFactory prometheusMetricsTrackerFactory(
        CollectorRegistry collectorRegistry) {
      // This makes it so that hikari metrics are in the same registry as other metrics
      return new PrometheusMetricsTrackerFactory(collectorRegistry);
    }

    @Autowired private PrometheusMetricsTrackerFactory prometheusMetricsTrackerFactory;

...
    public HikariDataSource dataSource(...) {
      HikariDataSource hikariDataSource = // create your HikariDataSource
      hikariDataSource.setMetricsTrackerFactory(this.prometheusMetricsTrackerFactory);
      return hikariDataSource;
    }
...
```
